# This is a basic workflow to help you get started with Actions

name: inventory-app CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
#set environment variables 
env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  APP_NAME: ${{ 'inventory-app-interim' }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-18.04
    steps:
    
    # Clone the repository
    - name: Checkout
      uses: actions/checkout@v2
      
      # Build Docker image
    - name: Docker build
      run: docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
      
      # Push the Docker image to Heroku Container Registry
    - name: Publish
      run: |
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_NAME
 
